var N = null;var sourcesIndex = {};
sourcesIndex["approx"] = {"name":"","files":["abs_diff_eq.rs","lib.rs","macros.rs","relative_eq.rs","ulps_eq.rs"]};
sourcesIndex["num_traits"] = {"name":"","dirs":[{"name":"ops","files":["checked.rs","inv.rs","mod.rs","mul_add.rs","saturating.rs","wrapping.rs"]}],"files":["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]};
sourcesIndex["palette"] = {"name":"","dirs":[{"name":"blend","files":["blend.rs","equations.rs","mod.rs","pre_alpha.rs"]},{"name":"encoding","dirs":[{"name":"pixel","files":["mod.rs","raw.rs"]}],"files":["gamma.rs","linear.rs","mod.rs","srgb.rs"]},{"name":"luma","files":["luma.rs","mod.rs"]},{"name":"rgb","files":["mod.rs","rgb.rs"]}],"files":["alpha.rs","chromatic_adaptation.rs","convert.rs","equality.rs","float.rs","gradient.rs","hsl.rs","hsv.rs","hues.rs","hwb.rs","lab.rs","lch.rs","lib.rs","macros.rs","matrix.rs","named.rs","white_point.rs","xyz.rs","yxy.rs"]};
sourcesIndex["palette_derive"] = {"name":"","dirs":[{"name":"convert","files":["from_color.rs","into_color.rs","mod.rs","shared.rs"]},{"name":"encoding","files":["mod.rs","pixel.rs"]}],"files":["lib.rs","meta.rs","util.rs"]};
sourcesIndex["phf"] = {"name":"","files":["lib.rs","map.rs","ordered_map.rs","ordered_set.rs","set.rs"]};
sourcesIndex["phf_shared"] = {"name":"","files":["lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["fallback.rs","lib.rs","strnom.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["siphasher"] = {"name":"","files":["lib.rs","sip.rs","sip128.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["gen_helper.rs","visit.rs"]}],"files":["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","tt.rs","ty.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
