(function() {var implementors = {};
implementors['void'] = ["impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='void/enum.Void.html' title='void::Void'>Void</a>",];implementors['serde'] = ["impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rustc_unicode/char/struct.DecodeUtf16Error.html' title='rustc_unicode::char::DecodeUtf16Error'>DecodeUtf16Error</a>","impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='serde/bytes/struct.ByteBuf.html' title='serde::bytes::ByteBuf'>ByteBuf</a>","impl&lt;'a&gt; <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='serde/bytes/struct.Bytes.html' title='serde::bytes::Bytes'>Bytes</a>&lt;'a&gt;","impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde/de/value/enum.Error.html' title='serde::de::value::Error'>Error</a>","impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde/de/enum.Type.html' title='serde::de::Type'>Type</a>",];implementors['string_cache'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='string_cache/atom/struct.Atom.html' title='string_cache::atom::Atom'>Atom</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='string_cache/namespace/struct.Namespace.html' title='string_cache::namespace::Namespace'>Namespace</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='string_cache/namespace/struct.QualName.html' title='string_cache::namespace::QualName'>QualName</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
