(function() {var implementors = {};
implementors['rustful'] = ["<a class='stability Stable' title='Stable'></a>impl&lt;S&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='https://hyperium.github.io/hyper/hyper/index.html/hyper/client/pool/struct.PooledStream.html' title='hyper::client::pool::PooledStream'>PooledStream</a>&lt;S&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'a, T&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='https://hyperium.github.io/hyper/hyper/index.html/hyper/server/response/struct.Response.html' title='hyper::server::response::Response'>Response</a>&lt;'a, T&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;T&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='https://hyperium.github.io/hyper/hyper/index.html/hyper/server/listener/struct.Sentinel.html' title='hyper::server::listener::Sentinel'>Sentinel</a>&lt;T&gt;","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rustful/server/struct.Listening.html' title='rustful::server::Listening'>Listening</a>","<a class='stability Stable' title='Stable'></a>impl&lt;'a, 'b&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rustful/response/struct.Response.html' title='rustful::response::Response'>Response</a>&lt;'a, 'b&gt;","<a class='stability Stable' title='Stable'></a>impl&lt;'a, 'b&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rustful/response/struct.ResponseWriter.html' title='rustful::response::ResponseWriter'>ResponseWriter</a>&lt;'a, 'b&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
