(function() {var implementors = {};
implementors['palette'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a class='struct' href='palette/struct.Rgb.html' title='palette::Rgb'>Rgb</a>&gt; for <a class='struct' href='palette/struct.Rgb.html' title='palette::Rgb'>Rgb</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for <a class='struct' href='palette/struct.Rgb.html' title='palette::Rgb'>Rgb</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a class='struct' href='palette/struct.Luma.html' title='palette::Luma'>Luma</a>&gt; for <a class='struct' href='palette/struct.Luma.html' title='palette::Luma'>Luma</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for <a class='struct' href='palette/struct.Luma.html' title='palette::Luma'>Luma</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a class='struct' href='palette/struct.Xyz.html' title='palette::Xyz'>Xyz</a>&gt; for <a class='struct' href='palette/struct.Xyz.html' title='palette::Xyz'>Xyz</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for <a class='struct' href='palette/struct.Xyz.html' title='palette::Xyz'>Xyz</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a class='struct' href='palette/struct.Lab.html' title='palette::Lab'>Lab</a>&gt; for <a class='struct' href='palette/struct.Lab.html' title='palette::Lab'>Lab</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;<a href='https://doc.rust-lang.org/nightly/std/primitive.f32.html'>f32</a>&gt; for <a class='struct' href='palette/struct.Lab.html' title='palette::Lab'>Lab</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
