(function() {var implementors = {};
implementors["buf_redux"] = ["impl&lt;R:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a>, Rs:&nbsp;<a class='trait' href='buf_redux/strategy/trait.ReadStrategy.html' title='buf_redux::strategy::ReadStrategy'>ReadStrategy</a>, Ms:&nbsp;<a class='trait' href='buf_redux/strategy/trait.MoveStrategy.html' title='buf_redux::strategy::MoveStrategy'>MoveStrategy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='buf_redux/struct.BufReader.html' title='buf_redux::BufReader'>BufReader</a>&lt;R, Rs, Ms&gt;",];
implementors["hyper"] = [];
implementors["libc"] = [];
implementors["mime_guess"] = [];
implementors["multipart"] = ["impl&lt;M:&nbsp;<a class='trait' href='multipart/server/trait.ReadEntry.html' title='multipart::server::ReadEntry'>ReadEntry</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='multipart/server/struct.MultipartFile.html' title='multipart::server::MultipartFile'>MultipartFile</a>&lt;M&gt;","impl&lt;R, Rs, Ms&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='buf_redux/struct.BufReader.html' title='buf_redux::BufReader'>BufReader</a>&lt;R, Rs, Ms&gt; <span class='where fmt-newline'>where Ms: <a class='trait' href='buf_redux/strategy/trait.MoveStrategy.html' title='buf_redux::strategy::MoveStrategy'>MoveStrategy</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R: <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rs: <a class='trait' href='buf_redux/strategy/trait.ReadStrategy.html' title='buf_redux::strategy::ReadStrategy'>ReadStrategy</a></span>",];
implementors["phf"] = [];
implementors["rustful"] = ["impl&lt;M&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='multipart/server/field/struct.MultipartFile.html' title='multipart::server::field::MultipartFile'>MultipartFile</a>&lt;M&gt; <span class='where fmt-newline'>where M: <a class='trait' href='multipart/server/field/trait.ReadEntry.html' title='multipart::server::field::ReadEntry'>ReadEntry</a></span>","impl&lt;R, Rs, Ms&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html' title='std::io::BufRead'>BufRead</a> for <a class='struct' href='buf_redux/struct.BufReader.html' title='buf_redux::BufReader'>BufReader</a>&lt;R, Rs, Ms&gt; <span class='where fmt-newline'>where Ms: <a class='trait' href='buf_redux/strategy/trait.MoveStrategy.html' title='buf_redux::strategy::MoveStrategy'>MoveStrategy</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R: <a class='trait' href='https://doc.rust-lang.org/nightly/std/io/trait.Read.html' title='std::io::Read'>Read</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rs: <a class='trait' href='buf_redux/strategy/trait.ReadStrategy.html' title='buf_redux::strategy::ReadStrategy'>ReadStrategy</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
